"""Added functionality to track which payment has been refunded

Revision ID: 3343751b22f1
Revises: 87becbc706b7
Create Date: 2022-05-09 21:18:13.210498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3343751b22f1'
down_revision = '87becbc706b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('refunded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'refunded')
    # ### end Alembic commands ###
