"""payment table

Revision ID: 87becbc706b7
Revises: 2b7fa3c9c85e
Create Date: 2022-05-09 17:44:08.889358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87becbc706b7'
down_revision = '2b7fa3c9c85e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_amount', sa.Integer(), nullable=True),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###
